name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 jetli/wasm-pack-action@v0.3.0
      with:
        version: "latest"
    - name: Build
      run: npm install && pushd wasm/physics-wasm && wasm-pack build && popd && npm run build
    
