name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install-wasmpack
      run : curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Install-npm
      run : npm install
    - name: Build-wasm
      working-directory: wasm/physics-wasm
      run : wasm-pack build
    - name: Build-npm
      run: npm run build
    
